version: "3.9"
services:
  nginx:
    build:
      context: ./elmclient          # 当前目录含 Dockerfile、nginx.conf、前端代码
      dockerfile: Dockerfile
    container_name: vue-nginx
    ports:
      - "8081:8081"
    networks:
      - mynetwork

networks:
  mynetwork:
