version: '3'
services:
  mysql:
    image: mysql:5.7
    container_name: mysql-elm
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - "3306:3306"
    volumes:
      - ./.mysql-data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    restart: always
    networks:
      - mynetwork

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: monitorjob  # 修改用户名为 monitorjob
      RABBITMQ_DEFAULT_PASS: sunnada.hzt123  # 修改密码为 sunnada.hzt123
      RABBITMQ_DEFAULT_VHOST: /monitorjob  # 可选，指定虚拟主机
    ports:
      - "5672:5672"  # AMQP 协议端口
      - "15672:15672"  # RabbitMQ 管理控制台端口
    volumes:
      - ./.rabbitmq-data:/var/lib/rabbitmq  # 数据存储卷
    networks:
      - mynetwork
    restart: always  # 自动重启

networks:
  mynetwork:
