erueka:
  instance:
    lease-expiration-duration-in-seconds: 30
    lease-renewal-interal-in-seconds: 5
eureka:
  client:
    service-url:
      defaultZone: http://localhost:13001/eureka/,http://localhost:13000/eureka
server:
  servlet:
    context-path: /elm

resilience4j:
  circuitbreaker:
    configs:
      default:
        automatic-transition-from-open-to-half-open-enabled: true
        failure-rate-threshold: 30
        minimum-number-of-calls: 2
        sliding-window-size: 10
        sliding-window-type: TIME_BASED
        wait-duration-in-open-state: 2s
      ignore-exception:
        - java.lang.Exception
    #      permitted-number-of-calls-in-half-open-state: 3
    instances:
      backendA:
        base-config: default

spring:
  application:
    name: business-consumer-server
  main:
    allow-bean-definition-overriding: true
  rabbitmq:
    host: localhost
    password: guest
    port: 5672
    username: guest
    virtual-host: /
service:
  provider:
    business:
      name: business-provider-server
