erueka:
  instance:
    lease-expiration-duration-in-seconds: 30
    lease-renewal-interal-in-seconds: 5
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server13001:13001/eureka/,http://eureka-server13000:13000/eureka
spring:
  application:
    name: business-provider-server
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: 123456
    url: jdbc:mysql://mysql-elm:3306/elm?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
  rabbitmq:
    host: rabbitmq
    password: sunnada.hzt123
    port: 5672
    username: monitorjob
    virtual-host: /monitorjob
logging:
  level:
    com:
      neusoft:
        elmcloud:
          mapper: debug
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.neusoft.elmcloud.po
